// Generates src/contract/types.gen.ts from the JSON Schema that Python writes (make ui-schema).
// `--check` fails instead of writing when the file is stale, so `npm run check` catches contract drift.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { compile } from "json-schema-to-typescript";

const dir = new URL("../src/contract/", import.meta.url);
const names = ["manifest", "watchlist", "dossier"];
const check = process.argv.includes("--check");

let out = "/* eslint-disable */\n// GENERATED by scripts/gen-types.mjs from src/contract/schema/*.json. Do not edit.\n// Source of truth: shadowfleet/ui_export/contract.py -> `make ui-schema`.\n\n";
const seen = new Set();

// Pydantic puts a `title` on every property; json2ts would turn each into its own named alias.
// Keep titles only on the root and on $defs (the real model names).
function stripTitles(node, keep) {
  if (Array.isArray(node)) return node.forEach((x) => stripTitles(x, false));
  if (node && typeof node === "object") {
    if (!keep) delete node.title;
    for (const [k, v] of Object.entries(node)) {
      if (k === "$defs") for (const d of Object.values(v)) stripTitles(d, true);
      else stripTitles(v, false);
    }
  }
}
for (const n of names) {
  const schema = JSON.parse(readFileSync(new URL(`schema/${n}.schema.json`, dir), "utf8"));
  const version = schema["x-contract-version"];
  delete schema.$id;
  stripTitles(schema, true);
  let ts = await compile(schema, schema.title, { bannerComment: "", additionalProperties: false, strictIndexSignatures: false, format: true, maxItems: -1 });
  for (const m of ts.matchAll(/^export (?:interface|type) (\w+)/gm)) {
    if (seen.has(m[1])) throw new Error(`type ${m[1]} is declared by two schemas; rename one model in contract.py`);
    seen.add(m[1]);
  }
  out += `// ---- ${n} (contract ${version})\n${ts}\n`;
  if (n === "manifest") out += `export const CONTRACT_VERSION = ${JSON.stringify(version)};\n\n`;
}
const target = new URL("types.gen.ts", dir);
if (check) {
  const cur = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (cur !== out) { console.error("src/contract/types.gen.ts is stale: run `npm run gen:types` (or make ui-schema)"); process.exit(1); }
  console.log("types.gen.ts is current");
} else {
  writeFileSync(target, out);
  console.log(`wrote ${target.pathname}`);
}
