/* eslint-disable */
// GENERATED by scripts/gen-types.mjs from src/contract/schema/*.json. Do not edit.
// Source of truth: shadowfleet/ui_export/contract.py -> `make ui-schema`.

// ---- manifest (contract 1.0.0)
export interface Manifest {
  contract_version: string;
  /**
   * @minItems 1
   */
  cutoffs: [CutoffInfo, ...CutoffInfo[]];
  default_label_set: "ofac_eu_uk" | "ofac_only";
  default_model: string;
  features: FeatureDef[];
  generated_at: string;
  k_values: number[];
  /**
   * @minItems 1
   */
  label_sets: ["ofac_eu_uk" | "ofac_only", ...("ofac_eu_uk" | "ofac_only")[]];
  /**
   * @minItems 1
   */
  models: [string, ...string[]];
  notes: string[];
  origin: "synthetic" | "live";
  overlays: Overlay[];
  /**
   * hull_ids that have a dossier file
   */
  vessels: string[];
  window_end: string;
  window_start: string;
}
export interface CutoffInfo {
  cutoff: string;
  horizon_closed: boolean;
  horizon_end: string;
  supervised: boolean;
}
export interface FeatureDef {
  description: string;
  family: "identity" | "ais" | "gfw" | "detect" | "static" | "graph" | "anomaly";
  name: string;
  post_hoc: boolean;
  source: "dma" | "gfw" | "self_built" | "sanctions";
}
/**
 * Static map context: configured anchorages, port zones, coverage areas (from config, never from labels).
 */
export interface Overlay {
  /**
   * lon_min, lat_min, lon_max, lat_max
   */
  bbox: [number, number, number, number, ...number[]] | null;
  kind: "anchorage" | "port" | "coverage";
  lat: number;
  lon: number;
  name: string;
  /**
   * value is a PLACEHOLDER in config.py, not a sourced polygon
   */
  placeholder: boolean;
}

export const CONTRACT_VERSION = "1.0.0";

// ---- watchlist (contract 1.0.0)
export interface Watchlist {
  contract_version: string;
  cutoff: string;
  label_set: "ofac_eu_uk" | "ofac_only";
  metrics: Metrics[];
  model: string;
  origin: "synthetic" | "live";
  population_size: number;
  rows: WatchlistRow[];
}
export interface Metrics {
  base_rate: number | null;
  n_positives: number | null;
  pr_auc: number | null;
  precision_at: {
    [k: string]: number | null;
  };
  recall_at: {
    [k: string]: number | null;
  };
  stratum: "all" | "b1";
}
export interface WatchlistRow {
  /**
   * B1 Russia-port rule fired at this cutoff
   */
  b1_stratum: boolean;
  /**
   * @maxItems 10
   */
  drivers: Driver[];
  flag_iso3: string | null;
  has_dossier: boolean;
  hull_id: string;
  imo: number | null;
  name: string | null;
  outcome: Outcome;
  rank: number;
  score: number;
}
/**
 * One SHAP contribution (Phase 6) or rule term (baselines) behind a score.
 */
export interface Driver {
  contribution: number;
  feature: string;
  value: number | null;
}
/**
 * Hindsight. The UI hides this unless the viewer turns on outcome reveal.
 */
export interface Outcome {
  designation_authorities: ("OFAC" | "EU" | "UK")[];
  designation_date: string | null;
  /**
   * null while the horizon is still open
   */
  label: (0 | 1) | null;
  /**
   * event-study lead time (plan ADR-11), hull level
   */
  lead_weeks: number | null;
}

// ---- dossier (contract 1.0.0)
export interface Dossier {
  contract_version: string;
  events: Event[];
  header: VesselHeader;
  hull_id: string;
  identity: IdentityInterval[];
  imo: number | null;
  origin: "synthetic" | "live";
  sanctions: SanctionAction[];
  scores: ScorePoint[];
  track: Track;
}
export interface Event {
  attrs: {
    [k: string]: string | number | boolean | null;
  };
  end: string;
  id: string;
  lat: number | null;
  lon: number | null;
  /**
   * when this record became knowable; the as-of filter key
   */
  observed_at: string;
  partner_hull_id: string | null;
  source: "dma" | "gfw" | "self_built" | "sanctions";
  start: string;
  summary: string;
  type:
    | "gap"
    | "encounter"
    | "loitering"
    | "port_visit"
    | "sts_candidate"
    | "anchorage_loitering"
    | "draught_inconsistency"
    | "identity_change"
    | "spoof_day";
}
export interface VesselHeader {
  beam_m: number | null;
  built_year: number | null;
  dwt: number | null;
  length_m: number | null;
  ship_type: string | null;
}
export interface IdentityInterval {
  callsign: string | null;
  end: string | null;
  flag_iso3: string | null;
  imo: number | null;
  mmsi: number | null;
  name: string | null;
  source: "dma" | "gfw" | "self_built" | "sanctions";
  start: string;
}
/**
 * Hindsight, like Outcome.
 */
export interface SanctionAction {
  action: "add" | "modify" | "remove";
  authority: "OFAC" | "EU" | "UK";
  date: string;
  program: string | null;
}
export interface ScorePoint {
  cutoff: string;
  model: string;
  population_size: number;
  rank: number | null;
  score: number;
}
/**
 * DMA positions, thinned for display. Columnar to keep files small. `t` is epoch seconds (UTC).
 */
export interface Track {
  draught: (number | null)[];
  lat: number[];
  lon: number[];
  sog: (number | null)[];
  t: number[];
}

